#!/usr/bin/env bash
# Generated by `brain install-hooks` — Stop hook.
# Reads the event JSON on stdin and stores the assistant response in the cache.
set -euo pipefail
ROOT="${CLAUDE_PROJECT_DIR:-$PWD}"
CLIENT="/home/lost/newproject/syswarden/.brain/brain-client.mjs"
command -v node >/dev/null 2>&1 || exit 0
cat | BRAIN_ROOT="$ROOT" node "$CLIENT" hook-stop 2>/dev/null || true
