#!/usr/bin/env bash
# Generated by `brain install-hooks` — UserPromptSubmit hook.
# Reads the event JSON on stdin, ensures the daemon is up, injects context.
set -euo pipefail
ROOT="${CLAUDE_PROJECT_DIR:-$PWD}"
CLIENT="/home/lost/newproject/syswarden/.brain/brain-client.mjs"
command -v node >/dev/null 2>&1 || exit 0   # no node → silent no-op
EVENT="$(cat)"
# Best-effort bootstrap: start the daemon if it is not responding.
if ! echo "$EVENT" | BRAIN_ROOT="$ROOT" node "$CLIENT" ping >/dev/null 2>&1; then
  brain --path "$ROOT" daemon start >/dev/null 2>&1 || true
fi
echo "$EVENT" | BRAIN_ROOT="$ROOT" node "$CLIENT" hook-prompt 2>/dev/null || true
